export * from './persona.model';
export * from './veterinario.model';
export * from './propietario.model';
export * from './tipo-animal.model';
export * from './mascotas.model';
export * from './programar-visita.model';
export * from './centro-veterinario.model';
export * from './visita-medico.model';
export * from './credenciales.model';
